export const NETWORK_CONFIG = {
  BACKEND_HOST: '192.168.1.17',
  BACKEND_PORT: 5000,
  FOOTBOARD_ESP_IP: '192.168.1.106',
} as const;

export const API_BASE_URL =
  `http://${NETWORK_CONFIG.BACKEND_HOST}:${NETWORK_CONFIG.BACKEND_PORT}/api`;

export const API_ORIGIN_URL =
  `http://${NETWORK_CONFIG.BACKEND_HOST}:${NETWORK_CONFIG.BACKEND_PORT}`;

export const WS_ORIGIN_URL =
  `ws://${NETWORK_CONFIG.BACKEND_HOST}:${NETWORK_CONFIG.BACKEND_PORT}`;
