export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  LOGOUT: '/auth/logout',
  REFRESH: '/auth/refresh',
  PROFILE_GET: '/profile',
  PROFILE_UPDATE: '/profile',
  PROFILE_DELETE: '/profile',
  CREATE_PARENT: '/parent/parent_register',
  LOCATION: '/profile/location',
  SCHOOLS: '/parent/schools',
  REGISTER_CHILD: "/parent/register_child",
  GET_MY_CHILD: "/parent/my-children",
  SHOW_ROUTES: "/assign/nearest-routes",
  ASSIGN_DRIVER: "/assign/assign-driver",
  PARENT_ATTENDANCE: '/parent/my-attendance',
  DECLARE_ATTENDANCE: '/parent/declare-attendance',
  GET_DECLARATION: '/parent/attendance-declaration',

  // Face Recognition
  FACE_REGISTER: '/face/register',
  FACE_STATUS: '/face/status',
  FACE_DELETE: '/face/register',
  FACE_SERVICE_STATUS: '/face/service/status',
} as const;